cargo-features = ["profile-overrides"]

[package]
name = "pumpkin-jam-2018"
version = "0.1.0"
authors = ["C Jones <code@calebjones.net>"]
edition = "2018"

[dependencies]
ggez = "0.4"
rand = "*"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"

[profile.dev.overrides."*"]
opt-level = 3
